version: '3.1'

services:

  db:
    image: mariadb:10.8.2
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: main_db
      MARIADB_USER: super_admin
      MARIADB_PASSWORD: super_admin_password
      # MARIADB_ROOT_HOST: 
      # volumes:
      #   - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
