version: '3.1'

services:

  db:
    image: mariadb:10.8.2
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: main_db
      MARIADB_USER: super_admin
      MARIADB_PASSWORD: super_admin_password
      # MARIADB_ROOT_HOST: 
      # volumes:
      #   - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tg_stop_propaganda:
    build: .
    restart: always
    environment:
      DB_USER: super_admin
      DB_PASS: super_admin_password
      DB_HOST: localhost
      DB_DBNAME: main_db
      TG_TOKEN: 5021755094:AAEdA8oon28Oi0R8qlRV6LY6Twjgmdi8l88
      TG_ADMIN: OlehBozhok
